# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Safing Docs
encoding: "utf-8"
lang: "en"
email: hello@safing.io
emailobfuscated: "=b!isfg>#nbjmup;ifmmpAtbgjoh/jp#?ifmmpAtbgjoh/jp=0b?"
description: > # this means to ignore newlines until "base_url:"
  Documentation for Safing Portmaster
base_url: "/" # the subpath of your site, e.g. /blog

### heavy externally referenced URLs
portmaster_settings_url: /portmaster/settings # Check reference in _data/menus.yml!
coc_url: /community/code-of-conduct

### assets
assets_url: /assets/
img_url: /assets/img/
vendor_url: /vendor/

### external
account_server_url: https://account.safing.io/
assets_server_url: https://assets.safing.io/
company_agreement_url: https://www.firmenmonitor.at/Secure/CompanyDetail.aspx?CID=761761
download_linux_deb_url: https://updates.safing.io/latest/linux_amd64/packages/portmaster-installer.deb
download_linux_arch_url: https://updates.safing.io/latest/linux_amd64/packages/portmaster-installer.pkg.tar.xz
download_windows_url: https://updates.safing.io/latest/windows_amd64/packages/portmaster-installer.exe
github_url: https://github.com/safing

github_pm_url: https://github.com/safing/portmaster
github_pm_ui_url: https://github.com/safing/portmaster-ui
github_pm_packaging_url: https://github.com/safing/portmaster-packaging
github_docs_url: https://github.com/safing/docs
github_web_url: https://github.com/safing/web

github_suggest_feature_url: /issues/new?assignees=&labels=feature&template=suggest-feature.md
github_report_bug_url: /issues/new?assignees=&labels=bug&template=bug-report.md
github_report_compatibility_url: /issues/new?assignees=&labels=in/compatibility&template=report-compatibility.md

github_linux_wiki_url: https://github.com/safing/portmaster/wiki/Linux
github_windows_wiki_url: https://github.com/safing/portmaster/wiki/Windows
invidious_channel_url: https://invidio.us/channel/UC_6TW053IlS4M22g7CxnukA
kickstarter_url: https://www.kickstarter.com/projects/safingio/spn
reddit_url: https://reddit.com/r/safing
twitter_url: https://twitter.com/SafingIO
youtube_channel_url: https://www.youtube.com/channel/UC_6TW053IlS4M22g7CxnukA

### website pages
website_url: https://safing.io/
about_url: https://safing.io/about/
blog_url: https://safing.io/blog/
backlog_url: https://safing.io/backlog/
community_hub_url: https://safing.io/community-hub/
contact_url: https://safing.io/contact/
esa_bic_url: https://safing.io/esa-bic/
help_url: https://safing.io/support/
newsletter_url: https://safing.io/newsletter/
ownership_url: https://safing.io/ownership/
business_model_url: https://safing.io/business-model/
podcast_url: https://safing.io/podcast/
portmaster_url: https://safing.io/portmaster/
privacy_url: https://safing.io/privacy/
next_page_url: https://safing.io/next/
spn_url: https://safing.io/spn/
team_url: https://safing.io/team/
terms_url: https://safing.io/terms/
video_url: https://safing.io/video/
whitepaper_url: https://safing.io/files/whitepaper/Gate17.pdf
vpn_comparison_url: https://safing.io/blog/2020/01/22/how-the-spn-compares-to-vpns/
tor_comparison_url: https://safing.io/blog/2020/01/22/how-the-spn-compares-to-tor/

url: "https://docs.safing.io" # the base hostname & protocol for your site
github_ref_base_url: "https://github.com/safing"
godoc_ref_base_url: "https://pkg.go.dev/github.com/safing"

# Build settings
markdown: kramdown
# theme: minima
# plugins:
#   - jekyll-feed

# Header anchors
before_heading: true
anchor_class: header-anchor
anchor_body: "<img src=\"/assets/img/icons/link.svg\">"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - .bundle/
